import type { Metadata } from "next";
import {Montserrat } from "next/font/google";
import "./globals.css";
import { CollapsedNavBar } from "../components/collapsedSidebar";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "HipertrApp",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <head>
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,300,0,0" />
      </head>
      <body className={montserrat.className}>
        <CollapsedNavBar />
        <div className="container">
          {children}
        </div>
      </body>
    </html>
  );
}
